"""
NAYAM (नयम्) — Audit Trail PDF Generation (Phase 4).

Generates formatted audit trail PDFs with multilingual support (English/Hindi).
Uses DejaVuSans font to support Unicode characters including Devanagari script.
"""

import io
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from fpdf import FPDF

from app.models.action_request import ActionRequest
from app.models.user import User


class AuditTrailPDF(FPDF):
    """Custom PDF class for audit trail reports with multilingual support."""

    def __init__(
        self,
        user: User,
        generated_at: datetime,
        include_hindi: bool = True,
    ):
        super().__init__()
        self.user = user
        self.generated_at = generated_at
        self.include_hindi = include_hindi
        self.page_number_offset = 0
        
        # Add DejaVuSans font for Unicode support (Devanagari, Latin, etc.)
        # Note: DejaVuSans.ttf should be available in the system or installed via fpdf2
        try:
            dejavu_path = Path("/System/Library/Fonts/DejaVuSans.ttf")
            if not dejavu_path.exists():
                # Fallback: use the font from fpdf2's built-in fonts
                import fpdf.fonts
                dejavu_path = Path(fpdf.fonts.__file__).parent / "DejaVu" / "DejaVuSans.ttf"
            
            if dejavu_path.exists():
                self.add_font("DejaVu", "", str(dejavu_path), uni=True)
                self.unicode_font = "DejaVu"
            else:
                # Fallback to Helvetica if DejaVuSans not found
                self.unicode_font = "Helvetica"
        except Exception:
            # Fallback if any error occurs
            self.unicode_font = "Helvetica"

    def header(self) -> None:
        """Page header with NAYAM branding and metadata."""
        # Title with Hindi if supported
        if self.unicode_font != "Helvetica":
            self.set_font(self.unicode_font, "B", 16)
            title_text = "NAYAM (नयम्)" if self.include_hindi else "NAYAM"
        else:
            self.set_font("Helvetica", "B", 16)
            title_text = "NAYAM"
        
        self.cell(0, 10, title_text, ln=True, align="C")
        
        # Subtitle
        if self.unicode_font != "Helvetica":
            self.set_font(self.unicode_font, "", 10)
            subtitle = "Governance Management System" if not self.include_hindi else "शासन प्रबंधन प्रणाली"
        else:
            self.set_font("Helvetica", "", 10)
            subtitle = "Governance Management System"
        
        self.cell(0, 5, subtitle, ln=True, align="C")

        # Separator line
        self.ln(2)
        self.set_draw_color(100, 100, 100)
        self.line(10, self.y, 200, self.y)
        self.ln(5)

        # Report metadata
        font_to_use = self.unicode_font if self.unicode_font != "Helvetica" else "Helvetica"
        self.set_font(font_to_use, "", 9)
        self.cell(0, 4, "Report Type: Audit Trail - Last 50 Actions", ln=True)
        self.cell(
            0,
            4,
            f"Generated: {self.generated_at.strftime('%Y-%m-%d %H:%M:%S %Z')}",
            ln=True,
        )
        self.cell(0, 4, f"Generated By: {self.user.name} ({self.user.role.value})", ln=True)
        self.cell(0, 4, f"Email: {self.user.email}", ln=True)
        self.ln(3)

    def footer(self) -> None:
        """Page footer with page number."""
        self.set_y(-15)
        font_to_use = self.unicode_font if self.unicode_font != "Helvetica" else "Helvetica"
        self.set_font(font_to_use, "", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

    def table_header(self) -> None:
        """Table header row."""
        font_to_use = self.unicode_font if self.unicode_font != "Helvetica" else "Helvetica"
        self.set_font(font_to_use, "B", 9)
        self.set_fill_color(200, 200, 200)
        self.set_text_color(0, 0, 0)

        # Column widths: Timestamp(30), Actor(30), Action Type(50), Type(25), Status(25)
        self.cell(30, 8, "Timestamp", border=1, fill=True)
        self.cell(30, 8, "Actor", border=1, fill=True)
        self.cell(50, 8, "Action", border=1, fill=True)
        self.cell(25, 8, "Type", border=1, fill=True)
        self.cell(25, 8, "Status", border=1, fill=True)
        self.ln()

    def table_row(
        self,
        timestamp: str,
        actor: str,
        action: str,
        action_type: str,
        status: str,
    ) -> None:
        """Add a row to the audit table."""
        font_to_use = self.unicode_font if self.unicode_font != "Helvetica" else "Helvetica"
        self.set_font(font_to_use, "", 8)
        self.set_text_color(0, 0, 0)

        # Check if we need a new page
        if self.y > 270:
            self.add_page()
            self.table_header()

        # Determine status color
        status_color = (100, 150, 100)  # green: approved
        if status == "PENDING":
            status_color = (200, 180, 80)  # yellow: pending
        elif status == "REJECTED":
            status_color = (200, 100, 100)  # red: rejected

        self.set_text_color(*status_color)

        self.cell(30, 7, timestamp, border=1)
        self.set_text_color(0, 0, 0)
        self.cell(30, 7, actor[:20], border=1)
        self.cell(50, 7, action[:30], border=1)
        self.cell(25, 7, action_type, border=1)
        self.set_text_color(*status_color)
        self.cell(25, 7, status, border=1)
        self.ln()
        self.set_text_color(0, 0, 0)


def generate_audit_trail_pdf(
    audit_entries: List[ActionRequest],
    user: User,
    generated_at: Optional[datetime] = None,
    include_hindi: bool = True,
) -> bytes:
    """
    Generate an audit trail PDF from ActionRequest records.

    Args:
        audit_entries: List of ActionRequest objects (up to 50).
        user: User who initiated the export.
        generated_at: Timestamp for the report. Defaults to now.
        include_hindi: Whether to include Hindi translations. Defaults to True.

    Returns:
        PDF bytes ready for download.
    """
    if generated_at is None:
        generated_at = datetime.now(timezone.utc)

    pdf = AuditTrailPDF(user=user, generated_at=generated_at, include_hindi=include_hindi)
    pdf.add_page()
    pdf.table_header()

    # Add each entry as a table row
    for entry in audit_entries:
        timestamp = entry.created_at.strftime("%Y-%m-%d %H:%M:%S") if entry.created_at else "N/A"
        actor = entry.requester.name if entry.requester else "Unknown"
        action = entry.action_type
        # Determine type: AI-generated (has agent_name) vs Human-initiated
        action_type = f"AI ({entry.agent_name[:8]})" if entry.agent_name else "Human"
        status = entry.status.value.upper()

        pdf.table_row(
            timestamp=timestamp,
            actor=actor,
            action=action,
            action_type=action_type,
            status=status,
        )

    # Render to bytes
    pdf_bytes = io.BytesIO()
    pdf.output(pdf_bytes)
    pdf_bytes.seek(0)
    return pdf_bytes.getvalue()
