"""
NAYAM (नयम्) — RiskScore ORM Model (Phase 3).

Stores per-ward risk assessments generated by the Predictive Governance
Engine.  Each record captures a snapshot of risk for a ward at a point
in time, enabling trend analysis and dashboard overlays.
"""

import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Column, DateTime, Enum, Float, Index, Integer, String, Text, Uuid,
)

from app.core.database import Base


class RiskLevel(str, enum.Enum):
    """Risk severity classification."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class RiskScore(Base):
    """
    Ward-level risk score produced by the predictive engine.

    Attributes:
        id:                UUID primary key.
        ward:              Administrative ward identifier.
        department:        Department context (e.g. "Water Supply").
        score:             Numeric risk value (0.0 – 100.0).
        risk_level:        Categorical severity.
        issue_count:       Number of issues in the scoring window.
        trend_direction:   Short label: "increasing", "stable", "decreasing".
        prediction_window: Description like "next_7_days".
        model_version:     Version of the scoring algorithm.
        computed_at:       Timestamp when this score was generated.
    """

    __tablename__ = "risk_scores"

    id = Column(Uuid, primary_key=True, default=uuid.uuid4, nullable=False)
    ward = Column(String(100), nullable=False)
    department = Column(String(255), nullable=True)
    score = Column(Float, nullable=False, default=0.0)
    risk_level = Column(
        Enum(RiskLevel, name="risk_level_enum", native_enum=False),
        nullable=False,
        default=RiskLevel.LOW,
    )
    issue_count = Column(Integer, nullable=False, default=0)
    trend_direction = Column(String(20), nullable=False, default="stable")
    prediction_window = Column(String(50), nullable=False, default="next_7_days")
    model_version = Column(String(50), nullable=False, default="v1.0")
    computed_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    __table_args__ = (
        Index("ix_risk_scores_ward", "ward"),
        Index("ix_risk_scores_department", "department"),
        Index("ix_risk_scores_risk_level", "risk_level"),
        Index("ix_risk_scores_computed_at", "computed_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<RiskScore(ward={self.ward}, score={self.score}, "
            f"level={self.risk_level}, computed_at={self.computed_at})>"
        )
