"""Add SLA tracking SQLite fix

Revision ID: 0e6e67e64f02
Revises: phase4_001
Create Date: 2026-03-20 20:16:34.148186
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e6e67e64f02'
down_revision: Union[str, None] = 'phase4_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('WARNING', 'ALERT', 'CRITICAL', name='anomaly_severity_enum', native_enum=False), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('deviation_percent', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_logs', schema=None) as batch_op:
        batch_op.create_index('ix_anomaly_logs_detected_at', ['detected_at'], unique=False)
        batch_op.create_index('ix_anomaly_logs_resolved', ['resolved'], unique=False)
        batch_op.create_index('ix_anomaly_logs_severity', ['severity'], unique=False)
        batch_op.create_index('ix_anomaly_logs_ward', ['ward'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'DECRYPT', 'EXPORT', 'APPROVE', 'REJECT', name='audit_action_enum', native_enum=False), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_resource_type', ['resource_type'], unique=False)
        batch_op.create_index('ix_audit_logs_user_id', ['user_id'], unique=False)

    op.create_table('citizens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.create_index('ix_citizens_name', ['name'], unique=False)
        batch_op.create_index('ix_citizens_ward', ['ward'], unique=False)

    op.create_table('embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_embeddings_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_embeddings_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_embeddings_source', ['source_type', 'source_id'], unique=False)

    op.create_table('encrypted_field_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.Enum('AES_256_GCM', 'FERNET', name='encryption_algo_enum', native_enum=False), nullable=False),
    sa.Column('key_reference', sa.String(length=255), nullable=False),
    sa.Column('encrypted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encrypted_field_registry', schema=None) as batch_op:
        batch_op.create_index('ix_enc_registry_encrypted_at', ['encrypted_at'], unique=False)
        batch_op.create_index('ix_enc_registry_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_enc_registry_field', ['field_name'], unique=False)

    op.create_table('geo_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('density_score', sa.Float(), nullable=False),
    sa.Column('dominant_department', sa.String(length=255), nullable=True),
    sa.Column('boundary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geo_clusters', schema=None) as batch_op:
        batch_op.create_index('ix_geo_clusters_center', ['center_lat', 'center_lng'], unique=False)
        batch_op.create_index('ix_geo_clusters_computed_at', ['computed_at'], unique=False)
        batch_op.create_index('ix_geo_clusters_density', ['density_score'], unique=False)
        batch_op.create_index('ix_geo_clusters_ward', ['ward'], unique=False)

    op.create_table('risk_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum', native_enum=False), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('trend_direction', sa.String(length=20), nullable=False),
    sa.Column('prediction_window', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.create_index('ix_risk_scores_computed_at', ['computed_at'], unique=False)
        batch_op.create_index('ix_risk_scores_department', ['department'], unique=False)
        batch_op.create_index('ix_risk_scores_risk_level', ['risk_level'], unique=False)
        batch_op.create_index('ix_risk_scores_ward', ['ward'], unique=False)

    op.create_table('task_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', 'EXECUTED', 'EXPIRED', name='recommendation_status_enum', native_enum=False), nullable=False),
    sa.Column('source_agent', sa.String(length=100), nullable=True),
    sa.Column('rationale', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_recommendations', schema=None) as batch_op:
        batch_op.create_index('ix_task_rec_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_task_rec_department', ['department'], unique=False)
        batch_op.create_index('ix_task_rec_priority', ['priority_score'], unique=False)
        batch_op.create_index('ix_task_rec_status', ['status'], unique=False)
        batch_op.create_index('ix_task_rec_ward', ['ward'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('LEADER', 'STAFF', 'ANALYST', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_role', ['role'], unique=False)

    op.create_table('action_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='action_status_enum', native_enum=False), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_requests', schema=None) as batch_op:
        batch_op.create_index('ix_action_requests_agent', ['agent_name'], unique=False)
        batch_op.create_index('ix_action_requests_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_requests_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_requests_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_action_requests_session_status', ['session_id', 'status'], unique=False)
        batch_op.create_index('ix_action_requests_status', ['status'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role_enum', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_conversations_user_session', ['user_id', 'session_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_documents_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('draft_type', sa.Enum('SPEECH', 'OFFICIAL_RESPONSE', 'PRESS_RELEASE', 'POLICY_BRIEF', 'MEETING_AGENDA', 'PUBLIC_NOTICE', 'LETTER', 'RTI_RESPONSE', 'CIRCULAR', name='draft_type_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('GENERATING', 'DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', name='draft_status_enum', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt_context', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('audience', sa.String(length=300), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index('ix_drafts_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_drafts_department', ['department'], unique=False)
        batch_op.create_index('ix_drafts_status', ['status'], unique=False)
        batch_op.create_index('ix_drafts_type', ['draft_type'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('MEETING', 'HEARING', 'SITE_VISIT', 'DEADLINE', 'REVIEW', 'PUBLIC_EVENT', 'OTHER', name='event_type_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='event_status_enum', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='event_priority_enum', native_enum=False), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('reminder_minutes', sa.String(length=10), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_department', ['department'], unique=False)
        batch_op.create_index('ix_events_start_time', ['start_time'], unique=False)
        batch_op.create_index('ix_events_status', ['status'], unique=False)
        batch_op.create_index('ix_events_type', ['event_type'], unique=False)

    op.create_table('execution_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.Enum('SUCCESS', 'PARTIAL', 'FAILURE', 'CANCELLED', name='feedback_outcome_enum', native_enum=False), nullable=False),
    sa.Column('outcome_detail', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('executed_by', sa.Uuid(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['task_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_exec_feedback_executed_at', ['executed_at'], unique=False)
        batch_op.create_index('ix_exec_feedback_outcome', ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_feedback_recommendation_id'), ['recommendation_id'], unique=False)

    op.create_table('issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citizen_id', sa.Uuid(), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED', name='issue_status_enum', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='issue_priority_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index('ix_issues_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_issues_department', ['department'], unique=False)
        batch_op.create_index('ix_issues_geo', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('ix_issues_priority', ['priority'], unique=False)
        batch_op.create_index('ix_issues_sla', ['sla_deadline'], unique=False)
        batch_op.create_index('ix_issues_status', ['status'], unique=False)

    with op.batch_alter_table('compliance_exports', schema=None) as batch_op:
        batch_op.alter_column('export_format',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('PDF', 'CSV', 'JSON', name='export_format_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'json'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='export_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'requested'"))
        batch_op.create_index('ix_compliance_exports_report_type', ['report_type'], unique=False)
        batch_op.create_index('ix_compliance_exports_requested_at', ['requested_at'], unique=False)

    with op.batch_alter_table('conflict_logs', schema=None) as batch_op:
        batch_op.alter_column('resolution',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'LOCAL_WINS', 'SERVER_WINS', 'MERGED', 'MANUAL', name='conflict_resolution_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.create_index('ix_conflict_logs_detected_at', ['detected_at'], unique=False)
        batch_op.create_index('ix_conflict_logs_resolution', ['resolution'], unique=False)

    with op.batch_alter_table('offline_actions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CACHED', 'QUEUED', 'SYNCED', 'FAILED', name='offline_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'cached'"))

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('API_LATENCY', 'DB_QUERY', 'SYNC_LATENCY', 'CACHE_HIT', 'MEMORY_USAGE', 'CPU_USAGE', 'ERROR_RATE', 'THROUGHPUT', name='metric_category_enum', native_enum=False),
               existing_nullable=False)
        batch_op.drop_index('ix_performance_metrics_category')
        batch_op.drop_index('ix_performance_metrics_endpoint')
        batch_op.drop_index('ix_performance_metrics_recorded_at')
        batch_op.create_index('ix_perf_metrics_category', ['category'], unique=False)
        batch_op.create_index('ix_perf_metrics_endpoint', ['endpoint'], unique=False)
        batch_op.create_index('ix_perf_metrics_node_id', ['node_id'], unique=False)
        batch_op.create_index('ix_perf_metrics_recorded_at', ['recorded_at'], unique=False)

    with op.batch_alter_table('rate_limit_records', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_records_client_ip')
        batch_op.drop_index('ix_rate_limit_records_created_at')
        batch_op.drop_index('ix_rate_limit_records_endpoint')
        batch_op.create_index('ix_rate_limit_blocked', ['blocked'], unique=False)
        batch_op.create_index('ix_rate_limit_client_ip', ['client_ip'], unique=False)
        batch_op.create_index('ix_rate_limit_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_rate_limit_endpoint', ['endpoint'], unique=False)
        batch_op.create_index('ix_rate_limit_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.alter_column('operation',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CREATE', 'UPDATE', 'DELETE', name='sync_operation_enum', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'SYNCED', 'FAILED', 'CONFLICT', name='sync_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'SYNCED', 'FAILED', 'CONFLICT', name='sync_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('operation',
               existing_type=sa.Enum('CREATE', 'UPDATE', 'DELETE', name='sync_operation_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('rate_limit_records', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_user_id')
        batch_op.drop_index('ix_rate_limit_endpoint')
        batch_op.drop_index('ix_rate_limit_created_at')
        batch_op.drop_index('ix_rate_limit_client_ip')
        batch_op.drop_index('ix_rate_limit_blocked')
        batch_op.create_index('ix_rate_limit_records_endpoint', ['endpoint'], unique=False)
        batch_op.create_index('ix_rate_limit_records_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_rate_limit_records_client_ip', ['client_ip'], unique=False)

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_perf_metrics_recorded_at')
        batch_op.drop_index('ix_perf_metrics_node_id')
        batch_op.drop_index('ix_perf_metrics_endpoint')
        batch_op.drop_index('ix_perf_metrics_category')
        batch_op.create_index('ix_performance_metrics_recorded_at', ['recorded_at'], unique=False)
        batch_op.create_index('ix_performance_metrics_endpoint', ['endpoint'], unique=False)
        batch_op.create_index('ix_performance_metrics_category', ['category'], unique=False)
        batch_op.alter_column('category',
               existing_type=sa.Enum('API_LATENCY', 'DB_QUERY', 'SYNC_LATENCY', 'CACHE_HIT', 'MEMORY_USAGE', 'CPU_USAGE', 'ERROR_RATE', 'THROUGHPUT', name='metric_category_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('offline_actions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('CACHED', 'QUEUED', 'SYNCED', 'FAILED', name='offline_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'cached'"))

    with op.batch_alter_table('conflict_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_conflict_logs_resolution')
        batch_op.drop_index('ix_conflict_logs_detected_at')
        batch_op.alter_column('resolution',
               existing_type=sa.Enum('PENDING', 'LOCAL_WINS', 'SERVER_WINS', 'MERGED', 'MANUAL', name='conflict_resolution_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('compliance_exports', schema=None) as batch_op:
        batch_op.drop_index('ix_compliance_exports_requested_at')
        batch_op.drop_index('ix_compliance_exports_report_type')
        batch_op.alter_column('status',
               existing_type=sa.Enum('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='export_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'requested'"))
        batch_op.alter_column('export_format',
               existing_type=sa.Enum('PDF', 'CSV', 'JSON', name='export_format_enum', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'json'"))

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index('ix_issues_status')
        batch_op.drop_index('ix_issues_sla')
        batch_op.drop_index('ix_issues_priority')
        batch_op.drop_index('ix_issues_geo')
        batch_op.drop_index('ix_issues_department')
        batch_op.drop_index('ix_issues_created_at')
        batch_op.drop_index(batch_op.f('ix_issues_citizen_id'))

    op.drop_table('issues')
    with op.batch_alter_table('execution_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_feedback_recommendation_id'))
        batch_op.drop_index('ix_exec_feedback_outcome')
        batch_op.drop_index('ix_exec_feedback_executed_at')

    op.drop_table('execution_feedback')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_type')
        batch_op.drop_index('ix_events_status')
        batch_op.drop_index('ix_events_start_time')
        batch_op.drop_index('ix_events_department')

    op.drop_table('events')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_drafts_type')
        batch_op.drop_index('ix_drafts_status')
        batch_op.drop_index('ix_drafts_department')
        batch_op.drop_index('ix_drafts_created_at')

    op.drop_table('drafts')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_uploaded_by'))
        batch_op.drop_index('ix_documents_created_at')

    op.drop_table('documents')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_user_session')
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_session_id'))
        batch_op.drop_index('ix_conversations_session_created')

    op.drop_table('conversations')
    with op.batch_alter_table('action_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_action_requests_status')
        batch_op.drop_index('ix_action_requests_session_status')
        batch_op.drop_index(batch_op.f('ix_action_requests_session_id'))
        batch_op.drop_index(batch_op.f('ix_action_requests_requested_by'))
        batch_op.drop_index('ix_action_requests_created_at')
        batch_op.drop_index('ix_action_requests_agent')

    op.drop_table('action_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('task_recommendations', schema=None) as batch_op:
        batch_op.drop_index('ix_task_rec_ward')
        batch_op.drop_index('ix_task_rec_status')
        batch_op.drop_index('ix_task_rec_priority')
        batch_op.drop_index('ix_task_rec_department')
        batch_op.drop_index('ix_task_rec_created_at')

    op.drop_table('task_recommendations')
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_scores_ward')
        batch_op.drop_index('ix_risk_scores_risk_level')
        batch_op.drop_index('ix_risk_scores_department')
        batch_op.drop_index('ix_risk_scores_computed_at')

    op.drop_table('risk_scores')
    with op.batch_alter_table('geo_clusters', schema=None) as batch_op:
        batch_op.drop_index('ix_geo_clusters_ward')
        batch_op.drop_index('ix_geo_clusters_density')
        batch_op.drop_index('ix_geo_clusters_computed_at')
        batch_op.drop_index('ix_geo_clusters_center')

    op.drop_table('geo_clusters')
    with op.batch_alter_table('encrypted_field_registry', schema=None) as batch_op:
        batch_op.drop_index('ix_enc_registry_field')
        batch_op.drop_index('ix_enc_registry_entity')
        batch_op.drop_index('ix_enc_registry_encrypted_at')

    op.drop_table('encrypted_field_registry')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_embeddings_source')
        batch_op.drop_index('ix_embeddings_created_at')
        batch_op.drop_index('ix_embeddings_content_hash')

    op.drop_table('embeddings')
    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.drop_index('ix_citizens_ward')
        batch_op.drop_index('ix_citizens_name')

    op.drop_table('citizens')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_user_id')
        batch_op.drop_index('ix_audit_logs_resource_type')
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('anomaly_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_anomaly_logs_ward')
        batch_op.drop_index('ix_anomaly_logs_severity')
        batch_op.drop_index('ix_anomaly_logs_resolved')
        batch_op.drop_index('ix_anomaly_logs_detected_at')

    op.drop_table('anomaly_logs')
    # ### end Alembic commands ###
